apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-api-gateway
  namespace: petclinic-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      imagePullSecrets:
        - name: ecr-secret
      initContainers:
        - name: wait-for-discovery
          image: busybox
          command: ['sh', '-c', 'until wget -q http://spring-petclinic-discovery-server:8761/actuator/health; do echo waiting; sleep 5; done']
      containers:
        - name: api-gateway
          image: 118821711881.dkr.ecr.af-south-1.amazonaws.com/spring-petclinic-g11-api-gateway:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-api-gateway
  namespace: petclinic-staging
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
